backend:
  name: github
  repo: rkmgpublishing/rkmg-elite
  branch: main
  base_url: https://rkmg-cms-auth.rkmadagency.workers.dev
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

